export default function Projects() {
  return (
    <div className="text-justify">
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it... Working on it... Working on it... Working on it...
      Working on it...{" "}
    </div>
  );
}
